### ISSUE TITLE
What screen resolution?

### ISSUE THREAD

**Issue by bharadwaj-raju** [Se7endAY/grub2-theme-vimix#1]
Which GRUB screen resolution will be optimal for this theme?

Default GRUB and 1024x768x24 resolutions make it appear a bit _stretched_.

**Comment by kalax2** [comment]
1920x1200(16:10) is better

**Comment by bharadwaj-raju** [comment]
Thanks!
P.S. What font?

**Comment by kalax2** [comment]
any font you like

**Comment by bharadwaj-raju** [comment]
I mean the one in the screenshot

**Comment by kalax2** [comment]
don't know :( .sorry.

**Comment by MobileAZN** [comment]
That font in the preview looks like Baron Neue:
http://www.dafont.com/baron-neue.font
