### ISSUE TITLE
Source has been updated

### ISSUE THREAD

**Issue by arcolinuxz** [Se7endAY/grub2-theme-vimix#11]
Hi,

Vince has been working on his vimix grub theme

Could you update your github?

thanks

Erik

**Comment by kalax2** [comment]
Updated.

**Comment by arcolinuxz** [comment]
Could you update the pkgbuild version ?

Now it says **20170904-1** on the AUR sounds old 2017 september

**Comment by kalax2** [comment]
The AUR package maintainer is not me. If you install it from AUR, it will get newest files from this repository.

**Comment by arcolinuxz** [comment]
Ok will tell the maintainer

Op do 14 feb. 2019 17:46 schreef Se7endAY <notifications@github.com:
