### ISSUE TITLE
Jump on item selection

### ISSUE THREAD

**Issue by Alexander-Shukaev** [Se7endAY/grub2-theme-vimix#5]
When item is selected, it and item below it experience movement.  Looks irritating.  Do you happen to know what's the cause of it?  Thank you.

**Comment by kalax2** [comment]
It works fine on my computer. Did you change any settings?

**Comment by Alexander-Shukaev** [comment]
No.  I didn't touch anything.  Maybe GRUB bug?

**Comment by kalax2** [comment]
I have no idea.

**Comment by Alexander-Shukaev** [comment]
I've created my own theme and based on the research done in the meantime I found out that this is caused by presence of northern and southern bitmaps for selection.  That is if one only uses west, east, and center, then the problem never occurs.  To use all nine pieces there either must be some strict sizing for padding/spacing/height or it is simply bugged due to certain GRUB version.  In my theme, I only use west, east, and center, and have no problem regardless of scale.
