### ISSUE TITLE
Problem with menu icons

### ISSUE THREAD

**Issue by sardus-X** [Se7endAY/grub2-theme-vimix#6]
Hi,
Nice minimal theme for grub. I installed the theme on a multiboot system with different linux  distributions (uefi mode) but when the grub menu appears at startup, the icons at each line do not match the logo icons of the different distributions but only a generic gnu-linux icon (a penguin) except that for the first distribution (main from which it is managed grub) with the ubuntu logo and not the correct one of linux mint.
Thanks for your help

**Comment by kalax2** [comment]
You can find out the reason of why logo of linux mint is not correct in /etc/default/grub.d/50_linuxmint.cfg.

### Solution
Open /boot/grub/grub.cfg with editor, and you will find some lines started with 'menuentry'. modify the value of --class option.

Example:
(before) `menuentry 'Linux Mint 18.2 Cinnamon 64-bit' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option`

(after) `menuentry 'Linux Mint 18.2 Cinnamon 64-bit' --class linux-mint --class gnu-linux --class gnu --class os $menuentry_id_option`

**Comment by sardus-X** [comment]
I have verified that in the /boot/grub/grub.cfg file the value of the --class option is "ubuntu" for linux mint distribution (main) and "gnu-linux" for all other distributions.
Is there a way to edit the /boot/grub/grub.cfg file (as You suggest) editing the /etc/default/grub file?
This issue only applies to uefi mode installations?

**Comment by kalax2** [comment]
@sardus-X It's not because of uefi mode.

1. backup the file `/etc/grub.d/30_os-prober`.
2. open this file with editor and add some lines like 5df5764.
3. update grub by running `sudo update-grub`.

**Comment by sardus-X** [comment]
> open this file with editor and add some lines like 5df5764.
Excuse me, i would like to make sure to understand well: do you mean to only "add" the three "green" lines
`+  CLASS="--class $(echo "${LABEL}" | LC_ALL=C sed 's,[[:digit:]]*$,,' | cut -d' ' -f1 | tr 'A-Z' 'a-z' | LC_ALL=C sed 's,[^[:alnum:]_],_,g')"`
`+`
`+menuentry '$(echo "$OS $onstr" | grub_quote)' $CLASS --class gnu-linux --class gnu --class os \$menuentry_id_option 'osprober-gnulinux-simple-$boot_device_id' {`
Or the third one is a line replacing the existing one?

**Comment by kalax2** [comment]
@sardus-X 

Add `CLASS="--class $(echo "${LABEL}" | LC_ALL=C sed 's,[[:digit:]]*$,,' | cut -d' ' -f1 | tr 'A-Z' 'a-z' | LC_ALL=C sed 's,[^[:alnum:]_],_,g')"` to your file before the line `gettext_printf "Found %s on %s\n" "${LONGNAME}" "${DEVICE}" >&2`.

Replace
 `menuentry '$(echo "$OS $onstr" | grub_quote)' --class gnu-linux --class gnu --class os \$menuentry_id_option 'osprober-gnulinux-simple-$boot_device_id' {` 
with 
`menuentry '$(echo "$OS $onstr" | grub_quote)' $CLASS --class gnu-linux --class gnu --class os \$menuentry_id_option 'osprober-gnulinux-simple-$boot_device_id' {`

**Comment by sardus-X** [comment]
I tested with linux mint 18.2 in vmware: edited the /etc/grub.d/30_os -prober file and updated the grub file but it looks like it has not changed the situation. The grub menu works but the icon is still Ubuntu and in the grub.cfg file the value of the --class option is "ubuntu" too

**Comment by kalax2** [comment]
@sardus-X 
1.Open the file /etc/grub.d/10_linux.
Replace
`CLASS="--class $(echo ${GRUB_DISTRIBUTOR} | tr 'A-Z' 'a-z' | cut -d' ' -f1|LC_ALL=C sed 's,[^[:alnum:]_],_,g') ${CLASS}"`
with
`CLASS="--class linux-mint ${CLASS}"`

2.Update grub.

**Comment by sardus-X** [comment]
After editing the /etc/grub.d/10_linux file seems to have duplicated the grub menu, however in order to better explain it I attached the grub menu image and the file /boot/grub/grub.cfg
![cattura](https://user-images.githubusercontent.com/29210004/28242980-9c9bed8a-69bb-11e7-808b-fdc5a483afda.PNG)
[grub.zip](https://github.com/Se7endAY/grub2-theme-vimix/files/1150666/grub.zip)

**Comment by kalax2** [comment]
@sardus-X move the backup file to another folder.

**Comment by sardus-X** [comment]
moved all backup files (/etc/grub.d/30_os-prober; /etc/grub.d/10_linux) to another folder but unfortunately no changes.
Edit: restored the original /etc/grub.d/30_os-prober file (it is correct or must be both edited?) and after grub update It looks like it works..:)
It could also works with multiple distributions on a multiboot system (as in my case?)
![screen2](https://user-images.githubusercontent.com/29210004/28245958-24cab91a-6a12-11e7-8eb4-98052ff61029.PNG)

**Comment by kalax2** [comment]
@sardus-X 
Yes, you also need to edit the `/etc/grub.d/30_os-prober` file.
